name: Mon Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Exécutez plusieurs commandes
      run: |
        echo "coding-style . ."

